
TARGET = Cavity
ROOT := ../..
FLAGS += -O3 -march=native -fopenmp
# FLAGS += -O3 -march=native -ffast-math
# FLAGS += -march=native
# FLAGS += -pg
FLAGS        += -DFLOAT_TYPE=double
include $(ROOT)/Makefile
