
TARGET = dambreak2d.exe
ROOT := ../..

FLAGS += -O3 -march=native -fopenmp
# FLAGS += -O3 -march=native
# FLAGS += -march=native
# FLAGS += -fopenmp
# FLAGS += -g
FLAGS += -DFLOAT_TYPE=double
# FLAGS += -DUNROLLFOR

OUTPUT += vtkoutput

include $(ROOT)/make.mk
