
TARGET = couette2d.exe
ROOT := ../..

FLAGS += -O3 -march=native -fopenmp
# FLAGS += -march=native
# FLAGS += -g
FLAGS += -DFLOAT_TYPE=double

# FLAGS += -O3 -march=native -ffast-math

OUTPUT += vtkoutput

include $(ROOT)/Makefile