
TARGET = codegen.exe
ROOT := ../../..

# FLAGS += -O3 -march=native -fopenmp
FLAGS += -Wall -Wno-unknown-pragmas -Wno-unused-local-typedefs
# FLAGS        += -g 
# FLAGS        += -D_FLB_DEBUG
FLAGS  += -DFLOAT_TYPE=double

# OUTPUT += vtkoutput STLoutput

include $(ROOT)/make.mk