
TARGET = dambreak3d.exe
ROOT := ../..

FLAGS += -O3 -march=native -fopenmp
# FLAGS += -O3 -march=native
# FLAGS += -march=native
# FLAGS += -g
FLAGS += -DFLOAT_TYPE=double

OUTPUT += vtkoutput STLoutput

include $(ROOT)/make.mk
