
TARGET = streamarr.exe
ROOT := ../../..

FLAGS += -O3 -march=native
# FLAGS += -Wall -Wno-unknown-pragmas -Wno-unused-local-typedefs
# FLAGS += -g -DMPI_DEBUG
# FLAGS += -g
# FLAGS += -pg
FLAGS += -DFLOAT_TYPE=float
# FLAGS += -DMPI_ENABLED

OUTPUT += vtkoutput

# CXXC := mpic++

include $(ROOT)/make.mk
