
TARGET = pipeinjection3d.exe
ROOT := ../..

FLAGS += -O3 -march=native -fopenmp
# FLAGS += -O3 -march=native
# FLAGS += -march=native
# FLAGS += -fopenmp
# FLAGS += -g
FLAGS += -DFLOAT_TYPE=double
FLAGS += -D_UNROLLFOR

OUTPUT += vtkoutput

include $(ROOT)/make.mk
