
TARGET = reader.exe
ROOT := ../../..

# FLAGS += -march=native -ffast-math
# FLAGS += -O3 -march=native #-fopenmp
# FLAGS +=  -march=native 
FLAGS += -march=native
# FLAGS += -DThread_Num 16 -fopenmp

# Uncomment to add debug symbols
FLAGS        += -g 
# FLAGS        += -D_FLB_DEBUG
FLAGS        += -DFLOAT_TYPE=double

OUTPUT += vtkoutput

include $(ROOT)/make.mk