
TARGET = mc.exe
ROOT := ../../..

# FLAGS += -O3 -march=native -fopenmp

FLAGS        += -g 
# FLAGS        += -D_FLB_DEBUG
FLAGS        += -DFLOAT_TYPE=double

OUTPUT += vtkoutput STLoutput

include $(ROOT)/make.mk