
TARGET = SDT
ROOT := ../..
# FLAGS += -march=native -ffast-math
# FLAGS += -O3 -march=native #-fopenmp
# FLAGS += -O3 -march=native -fopenmp
FLAGS +=  -O3 -march=native -fopenmp
# FLAGS += -DThread_Num 16 -fopenmp

# FLAGS += -D_COLLISION_P

# Uncomment to add debug symbols
# FLAGS        += -g 
# FLAGS        += -D_FLB_DEBUG
FLAGS        += -DFLOAT_TYPE=float

include $(ROOT)/Makefile