
TARGET = bddatatrans.exe
ROOT := ../../..

# FLAGS += -march=native -ffast-math
FLAGS += -O3 -march=native
# FLAGS += -O3 -march=native -fopenmp
# FLAGS += -march=native
# FLAGS += -DThread_Num 16 -fopenmp

# FLAGS += -D_COLLISION_P

# unused #pragma warning
# the order of member initialization not matching the order of member declaration in the class definition
# type comparison 

# FLAGS        += -Wall -Wno-unknown-pragmas -Wno-reorder -Wno-sign-compare -Wno-unused-variable

# Uncomment to add debug symbols
# FLAGS        += -g 
# FLAGS        += -D_FLB_DEBUG
FLAGS        += -DFLOAT_TYPE=double

OUTPUT += vtkoutput

include $(ROOT)/Makefile