
TARGET = Poiseuille
ROOT := ../..

FLAGS += -O3 -march=native  -fopenmp
# FLAGS += -D_COLLISION_P

# FLAGS += -O3 -march=native -ffast-math
# FLAGS += -DThread_Num=16 -fopenmp
# FLAGS        += -DFLOAT_TYPE=float
include $(ROOT)/make.mk