
TARGET = pipeinjection2d.exe
ROOT := ../..

FLAGS += -O3 -march=native -fopenmp
FLAGS += -Wall -Wdisabled-optimization -Wno-unknown-pragmas -Wno-unused-local-typedefs
# FLAGS += -O3 -march=native
# FLAGS += -march=native
# FLAGS += -fopenmp
# FLAGS += -g
FLAGS += -DFLOAT_TYPE=double

OUTPUT += vtkoutput

include $(ROOT)/make.mk
