
TARGET = cyclicarray.exe
ROOT := ../../..

FLAGS += -O2
FLAGS += -Wall -Wextra -Wno-unused-parameter

# -------------floating point type-------------
FLAGS += -DFLOAT_TYPE=double

include $(ROOT)/make.mk
