
TARGET = dambreak2d_intlat.exe
ROOT := ../..

# FLAGS += -O3 -march=native -fopenmp
FLAGS += -O3 -march=native
# FLAGS += -march=native
# FLAGS += -g
FLAGS += -DFLOAT_TYPE=double

OUTPUT += vtkoutput

include $(ROOT)/make.mk
