
TARGET = couette2d.exe
ROOT := ../..

FLAGS += -O3 -Wall -march=native -fopenmp
# FLAGS += -g
FLAGS += -DFLOAT_TYPE=double

# FLAGS += -O3 -march=native -ffast-math

OUTPUT += vtkoutput

include $(ROOT)/make.mk